name: Github Action Test

on:
  push:
    branches:
      - github_action_test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          docker run -u root -w /root -v ${{ github.workspace }}:/root curlimages/curl sh /root/init.sh
          md5sum data/trips/fhvhv_tripdata_2022-01.parquet
